### PR TITLE
Add vba.gm-modules public key

### PR DESCRIPTION
**Pull request by vbajs**
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

This PR add the public key for the repo https://github.com/vbajs/vba.gm-modules

Evidence that this repo is signed https://github.com/vbajs/vba.gm-modules/blob/main/dist/modules.json.sig
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEsDHisp7+d/IQg+jHKLligG/06/AFAmEHNXAACgkQKLligG/0
6/DTHhAAxjIGcnL67cJKvu+otSCd3qYCLQyP6RGzRruSjSdwos0dgAI8sPdDRroz
UQAJHngBeR8yOLggSH+S2kWfcupNQe/iqQYOrtRDlZlVuwbCEyXbPKc79uTA8n49
On2It7Bpl49KOGtivKf/KsGJ2PG2EcB0cUg7vNZXdpMawp2QYm5sAKZr44JFMPtN
r/FBDX5E0fZ389cSOcv58vEMtz9B+mcgRtpWXWgQJI1S5IfihwhmnZ+tj/1ulEnY
N0lMKBdhS8/a2nwgIavINtjXkfbHcFQQKl8TS8PVEAuBdlG1uDzcY9O+tNlVsUMM
Pyoad+J65lHpt2kXC9WY8YK8xa8YxHrnbTUYD16xrNkjQU66pFvO2MocHoBMygTh
+i43p2OwmBoqDY3uBWUzXjHjnKmb77Yjrhz19SJeWU/9jmt38R645LUJTKzmmGH+
BgJsvSbiiG7vuMmvHy71QGBv5HNN2kO+MPbE932qYZ3YuGamXFMRwNMa/iRxNGZU
Fm7CSIhlI/Rrv+UL6vxT+0AasajvF926leNsiZW/FgUZnqe8hRfVdcP0RVpNCEGU
klwjF5MIIoiTdhIpNHGXz3OqXlsX2LRj6Si+1NivctMI1va68+RAP/reKKv5uUUi
K5XrlW27TPvycuJdiey+8pDGXYVgxJhI0RfHyGxVI8pkJt9qaUk=
=hP9d
-----END PGP SIGNATURE-----

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Please sign your PR content to verify.

**Comment by vbajs** [comment]
Done

**Comment by CanadaHonk** [comment]
I meant the PR content as in the PR description here.

**Comment by vbajs** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Oh I get now
Updated PR descripton
Also signing this comment as well now
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEsDHisp7+d/IQg+jHKLligG/06/AFAmEHNjoACgkQKLligG/0
6/B2Wg//SAGAGufRiKfbvSccoXea9N/LjeI0Fxt+498lOkFtIM5Vai4VvyASxjkb
JpMLxGTt/OWFfXHgRunRwmO6tUijvZhrGUQZ/EJ/dCotW9oooOVGJf9SJinZwbI7
4AVSTKOyh2hNaO2hI2FXE+XLljcOEER7XMwFl0lQpIK3hZiyBX2rKHatG6vtQJ7I
q6nSZ7tjbwC0D3MNqsp/b4yXNuTeRZB0JCY3xQXN0u8NQVLZdViKEZ033aAyyMPS
j7c+5UaiB6GlRquZA/Jgc/NNVO33pZW27J2DNAp5cfkS5Sjblye+kqAcD92AZmhm
OnGCnRJviFSMz2A/hUGQyw8xuaNg8dNgVbZ54iPPUtsjQFxQyjn7+tw9jDnNXwaU
2xQ5VteUxZIqRXgUigmXPv4LqKS+kBq+yULQwEKo5TqjByQhNX8EIsiH0zEAof4l
R/aMTltOYkt21lx2hV24Xrtdlmeftj4snCDUjJRm9F1dXLnHthya95u8V1Us0GPS
LcIEt6ONkNmf8lm1suvPGa89T8hMASWsV2SveXfk2jcFrBOUB54DyaMALYxdyHiU
1WU+P57d2+m/6ur5wz0wpucvY+FA5SCu73bhRU+P/Qi+dIEHKQFzEsekuXSj30gr
8x7XMoW4dLySvPkW48IAWvuiU+erVCzzO0QgVet2bQVUii8Q0eY=
=U2cw
-----END PGP SIGNATURE-----

**Pull request merged**
